### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by skvoter** [racepwn/racepwn#2]
Привет
валится sigsegv при использовании ssl
все зависимости установлены, без ssl ошибок нет
config.json (хост разумеется изменен):
```
[
    {
        "race": {
            "type": "paralell", 
            "delay_time_usec": 10000, 
	    "last_chunk_size": 10
        },
        "body_type": "raw", 
        "raw": {
            "host": "tcp://example.com:443",
            "ssl": true,
            "race_param": [
                {
                    "data": "GET /some/freaking/path HTTP/1.1\r\nHost: example.com\r\n\r\n",
                    "count": 100
                }
            ]
        }
    }
]

```
Stack Trace:
```fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x6cba8b, 0x2a)
	/usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/usr/lib/go-1.10/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall]:
runtime.cgocall(0x628b80, 0xc42013bd20, 0xc400000000)
	/usr/lib/go-1.10/src/runtime/cgocall.go:128 +0x64 fp=0xc42013bcf0 sp=0xc42013bcb8 pc=0x4040c4
_/home/skvoter/utils/racepwn/racepwn/race._Cfunc_race_run(0x23b21e0, 0x0)
	_cgo_gotypes.go:94 +0x49 fp=0xc42013bd20 sp=0xc42013bcf0 pc=0x627499
_/home/skvoter/utils/racepwn/racepwn/race.Run.func8(0x23b21e0, 0x23b2230)
	/home/skvoter/utils/racepwn/racepwn/race/race.go:63 +0x56 fp=0xc42013bd58 sp=0xc42013bd20 pc=0x628176
_/home/skvoter/utils/racepwn/racepwn/race.Run(0xc42013be70, 0x6489e0, 0xc420114200)
	/home/skvoter/utils/racepwn/racepwn/race/race.go:63 +0x215 fp=0xc42013bdc8 sp=0xc42013bd58 pc=0x627b85
main.racepwnRun(0x6f4200, 0xc4200a2000, 0x0, 0x0, 0x6cb2a2)
	/home/skvoter/utils/racepwn/racepwn/racepwn.go:46 +0x22a fp=0xc42013bf40 sp=0xc42013bdc8 pc=0x6287ea
main.main()
	/home/skvoter/utils/racepwn/racepwn/racepwn.go:22 +0x6d fp=0xc42013bf88 sp=0xc42013bf40 pc=0x62849d
runtime.main()
	/usr/lib/go-1.10/src/runtime/proc.go:198 +0x212 fp=0xc42013bfe0 sp=0xc42013bf88 pc=0x42d5d2
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42013bfe8 sp=0xc42013bfe0 pc=0x457761
```

**Comment by mikhailbadin** [comment]
Спасибо за фидбек.
Починил. Теперь должно работать нормально.

**Comment by SalvaUkraincev** [comment]
Привет
Аналогичная ошибка, как починить?

**Comment by vyacheslavslava** [comment]
> Спасибо за фидбек.
> Починил. Теперь должно работать нормально.

Привет
Аналогичная ошибка, как починить?

**Comment by mikhailbadin** [comment]
Ошибка проявляется на свежей версии?

**Comment by vyacheslavslava** [comment]
> Ошибка проявляется на свежей версии?

Да

**Comment by mikhailbadin** [comment]
Спасибо!
Можете предоставить следующую информацию:
1. Пример конфига. Если необходимо уберите приватную информацию (например поля: *host* и *data*) 
2. Версию для следующих компонентов:
- ОС (`cat /etc/os-release`)
- Ядра (`uname -r`)
- clang и gcc, в зависимости от того, что стоит  (`gcc --version`)
- cmake (`cmake --version `)
- golang (`go version`)

**Comment by vyacheslavslava** [comment]
**Конфиг**
```
[
    {
        "race": {
            "type": "paralell",
            "delay_time_usec": 10000,
            "last_chunk_size": 10
        },
        "body_type": "raw",
        "raw": {
            "host": "tcp://host.com:443",
            "ssl": true,
            "race_param": [
                {
                    "data": "GET / HTTP/1.1\r\nHost: host.com\r\n\r\n",
                    "count": 10
                }
            ]
        }
    }
]
```

**cat /etc/os-release**
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**uname -r**
`4.15.0-1021-aws`

**clang --version**
```
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**gcc --version**
`gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0`

**cmake --version**
`cmake version 3.10.2`

**go version**
`go version go1.10.4 linux/amd64`
